### ISSUE TITLE
no in-game briefing text

### ISSUE THREAD

**Issue by ghost** [Masmblr/map-Nova_src#3]
From the [screenshots](https://github.com/Masmblr/map-Nova_src/blob/main/meta/preview_levelshots/1.jpg), I was expecting the mission screen to display the briefing text at some point. From the source code, I also was expecting a RoQ video file, but I could not find anything like this.
Was this removed or lost at some point?

**Comment by Masmblr** [comment]
Hi.
A RoQ video was initially planned but later discarded in favor of a shader solution. However, the designation remained. I tested the last release, and the briefing text is displayed correctly. Are you using a vanilla Tremulous installation? Some PK3 files may cause conflicts. I have included a recent screenshot as evidence.
![shot0001](https://github.com/Masmblr/map-Nova_src/assets/93756033/d7fc4563-8944-4da8-bb47-b947c2437702)

**Comment by ghost** [comment]
> Are you using a vanilla Tremulous installation? 

No, and this is why I am asking: I am fixing the many unvanquished bugs. I have nova almost working correctly, those days, and I do hope to be able to have at least all non-engine related things repaired.
Since it works in tremulous, then I'll close this issue, thanks for your time.

**Comment by ghost** [comment]
Ok, got it: I was using the version of the map you had in your ioquake3 big repo a little ago, and text.jpg was a WiP one. I'm going to properly setup my local repos.
